### ISSUE TITLE
Tutorial non completato

### ISSUE THREAD

**Issue by Gabbo144** [Fabio53443/CVVtoNotion#1]
Cosa devo fare per farlo funzionare? Immagino di dover cambiare il file js: in quali parti? E con quali elementi?

**Comment by Fabio53443** [comment]
npm run setup ;)
Dovrebbe settare tutto. è un po' che non lo uso lol

**Comment by Gabbo144** [comment]
> Notion To CVV@1.1.0 setup
> node ./src/setup.cjs

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'C:\Users\gabri\Downloads\CVVtoNotion-master\CVVtoNotion-master\src\setup.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.17.1

Ho provato a disinstallare e reinstallare node e npm, ma ancora niente

**Comment by Fabio53443** [comment]
Hai ragione, ho fatto un refactoring della struttura dei file ma ho dimenticato di cambiare il package.json. per ora basta che, dalla cartella fai `node setup.cjs`.In giornata risolvo.

**Comment by Fabio53443** [comment]
should be fixed ;D

**Comment by Gabbo144** [comment]
> Notion To CVV@1.1.0 sync
> node ./src/main.js

@notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }
C:\Users\gabri\Downloads\CVVtoNotion-master\node_modules\@notionhq\client\build\src\errors.js:162
        return new APIResponseError({
               ^

APIResponseError: API token is invalid.
    at buildRequestError (C:\Users\gabri\Downloads\CVVtoNotion-master\node_modules\@notionhq\client\build\src\errors.js:162:16)
    at Client.request (C:\Users\gabri\Downloads\CVVtoNotion-master\node_modules\@notionhq\client\build\src\Client.js:304:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///C:/Users/gabri/Downloads/CVVtoNotion-master/src/main.js:109:25)
    at async file:///C:/Users/gabri/Downloads/CVVtoNotion-master/src/main.js:119:1 {
  code: 'unauthorized',
  status: 401,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Mon, 04 Sep 2023 14:31:17 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '87' ],
      connection: [ 'close' ],
      'x-powered-by': [ 'Express' ],
      'x-notion-request-id': [ '524c5fcf-c8e5-4536-ab9b-b478898afc1a' ],
      etag: [ 'W/"57-QCRLT3IovYEW+CkwyJQlFtiXiG8"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      'set-cookie': [
        '__cf_bm=AZv8hmuDD56F8RKyjug92IR52BE2antMOfNja.hylVI-1693837877-0-Aa17MY4yb1wBhKb3varYgjSKI2OAtuDu1QqyHPk1iflXPK+iiH0p5WYlPWh5wGqLG59jQMbDVq9DdbkhsCUQ3fo=; path=/; expires=Mon, 04-Sep-23 15:01:17 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '8016ef6c0b934c57-MXP' ]
    }
  },
  body: '{"object":"error","status":401,"code":"unauthorized","message":"API token is invalid."}'
}

Node.js v18.17.1


Potrei essere stupido io hahaha, l'api token è quella che inizia con secret vero? Perchè la ho messa ma evidentemente non è corretta.

**Comment by Gabbo144** [comment]
Questo viene mostrato quando eseguo `npm run sync`. Ho provato a reinstallare, e le credenziali inserite quando seguo `npm run setup `sono corrette

**Comment by Gabbo144** [comment]
Ho riprovato con `node setup.cjs`, e stavolta quando eseguo `npm run sync `da un errore diverso: 
```
> Notion To CVV@1.1.0 sync
> node ./src/main.js

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'C:\Users\gabri\Desktop\CVVtoNotion-master\src\main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
Adesso provo a vedere se c'è qualche errore di collegamenti

**Comment by Fabio53443** [comment]
Ho ora sottomano il codice; rieseguo tutto da 0 e aggiusto se ci sono problemi. Ora come ora ti consiglio di riclonare la repo da 0 e vedere se va.

**Comment by Fabio53443** [comment]
Allora, update, essenzialmente il problema per la key è che node non riesce a settare variabili d'ambiente su windows con process.env integrato, quindi ora implemento una soluzione o con un secret.json o con un dotenv.

**Comment by Gabbo144** [comment]
Ok, grazie. Dimmi quando hai fatto che lo provo.

**Comment by Fabio53443** [comment]
Appena pushato il fix. per qualche motivo però ora sembra esserci qualche tipo di problema con la libreria su cui si basa il tutto che non sono in grado di capire e quindi risolvere. Odio javascript con tutto me stesso e se esistesse una libreria decente per CVV in python farei sicuramente con quella. 
Rant over. Fammi sapere se a te va per qualche motivo al di fuori della comprensione di noi esseri umani.

Il problema è legato ad una funzione `.getFullDate()` che secondo Node non esiste, e il codice upstream sembra corretto confrontandolo con soluzioni online dello stsso problema. Ora provo con node 20. Se persiste apro un issue upstream.

**Comment by Gabbo144** [comment]
https://github.com/MarcoBuster/ClasseVivaAPI
https://github.com/Lioydiano/Classeviva
potrebbero essercene altre

**Comment by Fabio53443** [comment]
Ho cancellato il commento perchè avevi pubblicato la chiave e una password. Ti consiglio di cambiare entrambi

**Comment by Gabbo144** [comment]
Oh caz sono ultra stupido, grazie mille. Ora cambio.

**Comment by Gabbo144** [comment]
Comunque continua a dire che la key non è valida

**Comment by Gabbo144** [comment]
```
> Notion To CVV@1.1.1 sync
> node ./src/main.js


     █▒▒    █▒▒         █▒▒ █▒▒         █▒▒        █▒▒                   █▒▒▒     █▒▒              █▒▒

  █▒▒   █▒▒  █▒▒       █▒▒   █▒▒       █▒▒         █▒▒                   █▒ █▒▒   █▒▒              █▒▒    █▒

 █▒▒          █▒▒     █▒▒     █▒▒     █▒▒        █▒█▒ █▒    █▒▒          █▒▒ █▒▒  █▒▒    █▒▒     █▒█▒ █▒        █▒▒     █▒▒ █▒▒
 █▒▒           █▒▒   █▒▒       █▒▒   █▒▒           █▒▒    █▒▒  █▒▒       █▒▒  █▒▒ █▒▒  █▒▒  █▒▒    █▒▒   █▒▒  █▒▒  █▒▒   █▒▒  █▒▒
 █▒▒            █▒▒ █▒▒         █▒▒ █▒▒            █▒▒   █▒▒    █▒▒      █▒▒   █▒ █▒▒ █▒▒    █▒▒   █▒▒   █▒▒ █▒▒    █▒▒  █▒▒  █▒▒
  █▒▒   █▒▒      █▒▒▒▒           █▒▒▒▒             █▒▒    █▒▒  █▒▒       █▒▒    █▒ ▒▒  █▒▒  █▒▒    █▒▒   █▒▒  █▒▒  █▒▒   █▒▒  █▒▒
    █▒▒▒▒         █▒▒             █▒▒               █▒▒     █▒▒          █▒▒      █▒▒    █▒▒        █▒▒  █▒▒    █▒▒     █▒▒▒  █▒▒


Version: 1.1.1

██████╗ ███████╗██╗    ██╗ █████╗ ██████╗ ███████╗██╗
██╔══██╗██╔════╝██║    ██║██╔══██╗██╔══██╗██╔════╝██║
██████╔╝█████╗  ██║ █╗ ██║███████║██████╔╝█████╗  ██║
██╔══██╗██╔══╝  ██║███╗██║██╔══██║██╔══██╗██╔══╝  ╚═╝
██████╔╝███████╗╚███╔███╔╝██║  ██║██║  ██║███████╗██╗
╚═════╝ ╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝

There is sensitive data below, such as your Notion API key and your CVV login. Redact before posting.

Notion API key: secret_*api key* Notion database ID: *id*CVV login: *cvv login* CVV password: *cvv password*

@notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }
C:\Users\gabri\Downloads\CVVtoNotion-master\node_modules\@notionhq\client\build\src\errors.js:162
        return new APIResponseError({
               ^

APIResponseError: API token is invalid.
    at buildRequestError (C:\Users\gabri\Downloads\CVVtoNotion-master\node_modules\@notionhq\client\build\src\errors.js:162:16)
    at Client.request (C:\Users\gabri\Downloads\CVVtoNotion-master\node_modules\@notionhq\client\build\src\Client.js:304:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///C:/Users/gabri/Downloads/CVVtoNotion-master/src/main.js:135:25)
    at async file:///C:/Users/gabri/Downloads/CVVtoNotion-master/src/main.js:145:1 {
  code: 'unauthorized',
  status: 401,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Wed, 06 Sep 2023 21:30:55 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '87' ],
      connection: [ 'close' ],
      'x-powered-by': [ 'Express' ],
      'x-notion-request-id': [ 'aaa12c14-ab66-42e3-9628-ee9e24e4cd6e' ],
      etag: [ 'W/"57-QCRLT3IovYEW+CkwyJQlFtiXiG8"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      'set-cookie': [
        '__cf_bm=TquskoNngVxEE46PYEfvcxLPP0ulacSHd0cDVlJbroY-1694035855-0-Ad0ge1itu023GMrHQ9Vtuovi8ONMPQln4HHk5Esla2vJO0vUbToIk+j2fGYJXXlhO/LBTHCTZUozIRRfOtm9hEE=; path=/; expires=Wed, 06-Sep-23 22:00:55 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '8029d0de3eee5a07-MXP' ]
    }
  },
  body: '{"object":"error","status":401,"code":"unauthorized","message":"API token is invalid."}'
}

Node.js v18.17.1
```
Questo è il risultato (ho censurato i dati sensibili)

**Comment by Fabio53443** [comment]
Hai collegato l'integration al database?
[image: image.png]
L'unica cosa che mi viene in mente... A me il login lo fa ma si rompe
quando inizializza l'API Classevivia.js

**Comment by Fabio53443** [comment]
Questo è lo stato delle cose ora come ora; aprirò un issue nella repo upstream quando ho tempo e si spera che si possa risolvere.
```js
> Notion To CVV@1.1.1 sync
> node ./src/main.js


     █▒▒    █▒▒         █▒▒ █▒▒         █▒▒        █▒▒                   █▒▒▒     █▒▒              █▒▒
  █▒▒   █▒▒  █▒▒       █▒▒   █▒▒       █▒▒         █▒▒                   █▒ █▒▒   █▒▒              █▒▒    █▒
 █▒▒          █▒▒     █▒▒     █▒▒     █▒▒        █▒█▒ █▒    █▒▒          █▒▒ █▒▒  █▒▒    █▒▒     █▒█▒ █▒        █▒▒     █▒▒ █▒▒  
 █▒▒           █▒▒   █▒▒       █▒▒   █▒▒           █▒▒    █▒▒  █▒▒       █▒▒  █▒▒ █▒▒  █▒▒  █▒▒    █▒▒   █▒▒  █▒▒  █▒▒   █▒▒  █▒▒
 █▒▒            █▒▒ █▒▒         █▒▒ █▒▒            █▒▒   █▒▒    █▒▒      █▒▒   █▒ █▒▒ █▒▒    █▒▒   █▒▒   █▒▒ █▒▒    █▒▒  █▒▒  █▒▒
  █▒▒   █▒▒      █▒▒▒▒           █▒▒▒▒             █▒▒    █▒▒  █▒▒       █▒▒    █▒ ▒▒  █▒▒  █▒▒    █▒▒   █▒▒  █▒▒  █▒▒   █▒▒  █▒▒
    █▒▒▒▒         █▒▒             █▒▒               █▒▒     █▒▒          █▒▒      █▒▒    █▒▒        █▒▒  █▒▒    █▒▒     █▒▒▒  █▒▒


Version: 1.1.1

██████╗ ███████╗██╗    ██╗ █████╗ ██████╗ ███████╗██╗
██╔══██╗██╔════╝██║    ██║██╔══██╗██╔══██╗██╔════╝██║
██████╔╝█████╗  ██║ █╗ ██║███████║██████╔╝█████╗  ██║
██╔══██╗██╔══╝  ██║███╗██║██╔══██║██╔══██╗██╔══╝  ╚═╝
██████╔╝███████╗╚███╔███╔╝██║  ██║██║  ██║███████╗██╗
╚═════╝ ╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝

There is sensitive data below, such as your Notion API key and your CVV login. Redact before posting.

Notion API key: xxxx Notion database ID: xxxx login: xx@xxxxx.com CVV password: xxxxx

C:\Users\Fabio\Desktop\CVVtoNotion\CVVtoNotion\node_modules\classeviva.js\dist\src\classes\Rest.js:600
        const year = date.getFullYear();
                          ^

TypeError: date.getFullYear is not a function
    at #formatDate (C:\Users\Fabio\Desktop\CVVtoNotion\CVVtoNotion\node_modules\classeviva.js\dist\src\classes\Rest.js:600:27)
    at Rest.getAgenda (C:\Users\Fabio\Desktop\CVVtoNotion\CVVtoNotion\node_modules\classeviva.js\dist\src\classes\Rest.js:161:90)
    at agendafun (file:///C:/Users/Fabio/Desktop/CVVtoNotion/CVVtoNotion/src/main.js:66:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/Fabio/Desktop/CVVtoNotion/CVVtoNotion/src/main.js:149:14

Node.js v18.17.1
```

**Comment by Fabio53443** [comment]
Comunque chiuderò qui questo issue perchè è OT dal titolo. Ne aprirò un altro dedicato a questo.

**Comment by Gabbo144** [comment]
Sì, ho collegato. Adesso riproverò

**Comment by Fabio53443** [comment]
Pls apri un nuovo issue se continua ad essere rotto:)

(ps ho sistemato la cosa della data, quindi ora come ora a me funziona tutto tranne che la mia scuola ancora non avvia l'anno scolastico quindi l'agenda ancora non esiste)
